from .encoderDecoderBlock import PositionWiseFeedForward
from .encoderDecoderBlock import MultiHeadAttention

import torch
import torch.nn as nn

class Decoder(nn.Module):
    """
    ### Decoder

    ##### Explanation
    `This is a continuation of the explanation of the encoder.`

    After the translator understands what the source is they start to write down the translated speech word by word. The page starts empty(<start> token in the case of transformers) and the translator writes down the first word, with the context of the first word and the meaning in mind the translator writes the next word and so on until the sentence is over.
    """
    def __init__(self, embeddingSize:int, headCount:int, dff:int, dropout:float) -> None:
        super().__init__()

        self.selfAttention = MultiHeadAttention(embeddingSize, headCount)
        self.norm1 = nn.LayerNorm(embeddingSize)

        self.crossAttention = MultiHeadAttention(embeddingSize, headCount)
        self.norm2 = nn.LayerNorm(embeddingSize)

        self.feedForward = PositionWiseFeedForward(embeddingSize, dff)
        self.norm3 = nn.LayerNorm(embeddingSize)

        self.dropout = nn.Dropout(dropout)

    def forward(self, x:torch.Tensor, encoderOutput:torch.Tensor, sourceMask:torch.Tensor, targetMask:torch.Tensor):
        """Decodes the text to our format

        Args:
            x (torch.Tensor): Positional encoded embedding of output generated so far by the transformer, if it is starting we have a <start> token
            encoderOutput (torch.Tensor): Output generated by the encoder
            sourceMask (torch.Tensor): This is to weed out all the padding tokens
            targetMask (torch.Tensor): This is to prevent the decoder from looking ahead

        Returns:
            torch.Tensor: Decoded output
        """
        
        selfAttention = self.dropout(self.selfAttention(x, x, x, targetMask))
        x = x + self.norm1(selfAttention)
        crossAttention = self.dropout(self.crossAttention(x, encoderOutput, encoderOutput, sourceMask))
        x = x + self.norm2(crossAttention)
        ff = self.dropout(self.feedForward(x))
        
        return self.norm3(x + ff)